version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: nuqui
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appuser_password
    ports:
      - "5432:5432"

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: appuser
      RABBITMQ_DEFAULT_PASS: appuser_password
      # RABBITMQ_DEFAULT_VHOST: /nuquivhost
    ports:
      - "5672:5672"
      - "15672:15672"
    # volumes:
    #   - ./rabbitmq-config:/etc/rabbitmq