version: '3'

services:
  nuqui_postgres_humans:
    image: postgres:latest
    container_name: nuqui_postgres_humans
    environment:
      POSTGRES_DB: nuqui
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appuser_password
    ports:
      - "5432:5432"

  nuqui_postgres_deposits:
    image: postgres:latest
    container_name: nuqui_postgres_deposits
    environment:
      POSTGRES_DB: nuqui_deposits
      POSTGRES_USER: another_appuser
      POSTGRES_PASSWORD: another_appuser_password
    ports:
      - "5433:5432"

  nuqui_dynamodb_users:
    image: "amazon/dynamodb-local:latest"
    container_name: nuqui_dynamodb_users
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID="your1access2key3id"
      - AWS_SECRET_ACCESS_KEY="your1secret2key"
      - AWS_DEFAULT_REGION=us-east-1

  nuqui_rabbitmq:
    image: rabbitmq:3.8-management
    container_name: nuqui_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: appuser
      RABBITMQ_DEFAULT_PASS: appuser_password
    ports:
      - "5672:5672"
      - "15672:15672"


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: nuquilogs
    ports:
      - "27017:27017"
    networks:
      - MONGO
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "8023:8081"
    networks:
      - MONGO
    depends_on:
      - mongo

networks:
  MONGO:
    name: MONGO